---
image:
  name: "major1201/k8s-mutator:latest"
  pullPolicy: Always

webhook:
  name: k8s-mutator.example.com
  failurePolicy: Ignore
#  namespaceSelector:
#    matchLabels:
#      name: default

config:
  annotationKey: k8s-mutator.example.com/requests
  strategies:
    - name: filebeat
      patches:
        # add filebeat sidecar
        - isTemplate: true
          data: |
            op: add
            path: /spec/containers/-
            value:
              name: filebeat
              image: myrepo/filebeat
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 100m
                  memory: 128Mi
              volumeMounts:
                - name: logs
                  mountPath: "/var/log/{{ .Pod.Labels.name }}"
  rules:
    - namespace:
        - default
      selector:
        k8s-app: myapp
      strategies:
        - filebeat

certificates:
  caBundle: "!!! your base64 encoded cabundle here !!!"
  cert: |
    -----BEGIN CERTIFICATE-----
    YOUR_CERTIFICATE_HERE
    -----END CERTIFICATE-----
  key: |
    -----BEGIN RSA PRIVATE KEY-----
    YOUR_PRIVATE_KEY_HERE
    -----END RSA PRIVATE KEY-----

service:
  type: ClusterIP
#  additionalPorts:
#    - name: tcp
#      port: 7000
#      targetPort: 7000
#      protocol: TCP

serviceMonitor:
  enabled: false
