apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    k8s-app: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      k8s-app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        k8s-app: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      containers:
      - name: "k8s-mutator"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: {{ .Values.image.name }}
        ports:
        - name: https
          containerPort: 443
        volumeMounts:
        - name: config
          mountPath: /etc/k8s-mutator
      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}
