{{- if .Values.serviceMonitor.enabled -}}
# NOTE: this describes how prometheus finds your Service for your app
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  labels:
    k8s-app: {{ .Release.Name }}
spec:
  endpoints:
  - honorLabels: true
    port: http-metrics
    path: "/metrics"
    interval: 30s
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      k8s-app: {{ .Release.Name }}
{{- end }}
