apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-mutator
subjects:
  - kind: ServiceAccount
    name: k8s-mutator
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: k8s-mutator
  apiGroup: rbac.authorization.k8s.io
