apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubemutator
subjects:
  - kind: ServiceAccount
    name: kubemutator
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: kubemutator
  apiGroup: rbac.authorization.k8s.io
