apiVersion: apps/v1
kind: Deployment
metadata:
  name: "kubemutator"
  namespace: "kube-system"
  labels:
    k8s-app: "kubemutator"
spec:
  selector:
    matchLabels:
      k8s-app: "kubemutator"
  template:
    metadata:
      labels:
        k8s-app: "kubemutator"
    spec:
      serviceAccountName: kubemutator
      containers:
      - name: "kubemutator"
        imagePullPolicy: Always
        image: "major1201/kubemutator:latest"
        ports:
        - name: https
          containerPort: 443
        volumeMounts:
        - name: config
          mountPath: /etc/kubemutator
      volumes:
      - name: config
        configMap:
          name: kubemutator
